version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./MySQL/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db